######################################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
######################################################################################################

# VSS Deployment with Twelve Labs Integration
# This configuration uses Twelve Labs cloud services for video search (Marengo) and summarization (Pegasus)

services:
  via-server:
    # image: ${VIA_IMAGE:-nvcr.io/nvidia/blueprint/vss-engine:2.3.1}
    build:
      context: ../../../src/vss-engine
      dockerfile: docker/Dockerfile
      args:
        BASE_IMAGE: ${VIA_IMAGE:-nvcr.io/nvidia/blueprint/vss-engine:2.3.1}
    shm_size: '16gb'

#    Disabled GPU deployment for Twelve Labs integration.

#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [gpu]
    ports:
      - "${BACKEND_PORT?}:${BACKEND_PORT?}"
      - "${FRONTEND_PORT?}:${FRONTEND_PORT?}"
    volumes:
      - "${ASSET_STORAGE_DIR:-/dummy}${ASSET_STORAGE_DIR:+:/tmp/assets}"
      - "${CA_RAG_CONFIG:-/dummy}${CA_RAG_CONFIG:+:/opt/nvidia/via/default_config.yaml}"
      - "${GUARDRAILS_CONFIG:-/dummy}${GUARDRAILS_CONFIG:+:/opt/nvidia/via/guardrails_config}"
      - "${GRAPH_RAG_PROMPT_CONFIG:-/dummy}${GRAPH_RAG_PROMPT_CONFIG:+:/opt/nvidia/via/warehouse_graph_rag_config.yaml}"
      - "${EXAMPLE_STREAMS_DIR:-/dummy}${EXAMPLE_STREAMS_DIR:+:/opt/nvidia/via/streams:ro}"
      - "${MILVUS_DATA_DIR:-/dummy}${MILVUS_DATA_DIR:+:/root/.milvus.io/milvus-server/2.3.5}"
      - "${MODEL_ROOT_DIR:-/dummy}${MODEL_ROOT_DIR:+:${MODEL_ROOT_DIR:-}}"
      - "${NGC_MODEL_CACHE:-via-ngc-model-cache}:/root/.via/ngc_model_cache"
      - "${TRT_ENGINE_PATH:-/dummy}${TRT_ENGINE_PATH:+:${TRT_ENGINE_PATH:-}}"
      - "${GSAM_MODEL_ROOT_DIR:-/dummy}${GSAM_MODEL_ROOT_DIR:+:${GSAM_MODEL_ROOT_DIR:-}}"
      - "${VIA_SRC_DIR:-/dummy}${VIA_SRC_DIR:+:/opt/nvidia/via:ro}"
      - "${VIA_LOG_DIR:-/dummy}${VIA_LOG_DIR:+:/tmp/via-logs}"
      - via-hf-cache:/tmp/huggingface
      - "${CV_PIPELINE_TRACKER_CONFIG:-/dummy}${CV_PIPELINE_TRACKER_CONFIG:+:/opt/nvidia/via/config/default_tracker_config.yml}"
    environment:
      # Twelve Labs Configuration
      TWELVE_LABS_API_KEY: "${TWELVE_LABS_API_KEY}"
      TWELVE_LABS_API_URL: "${TWELVE_LABS_API_URL}"
      TWELVE_LABS_MARENGO_INDEX_NAME: "${TWELVE_LABS_MARENGO_INDEX_NAME}"
      TWELVE_LABS_PEGASUS_INDEX_NAME: "${TWELVE_LABS_PEGASUS_INDEX_NAME}"
      TWELVE_LABS_MARENGO_MODEL: "${TWELVE_LABS_MARENGO_MODEL}"
      TWELVE_LABS_PEGASUS_MODEL: "${TWELVE_LABS_PEGASUS_MODEL}"
      TWELVE_LABS_MARENGO_OPTIONS: "${TWELVE_LABS_MARENGO_OPTIONS}"
      TWELVE_LABS_PEGASUS_OPTIONS: "${TWELVE_LABS_PEGASUS_OPTIONS}"
      TWELVE_LABS_SEARCH_OPTIONS: "${TWELVE_LABS_SEARCH_OPTIONS}"
      TWELVE_LABS_MAX_CLIPS: "${TWELVE_LABS_MAX_CLIPS}"
      TWELVE_LABS_UPLOAD_TIMEOUT: "${TWELVE_LABS_UPLOAD_TIMEOUT}"
      VSS_ENABLE_TWELVE_LABS_AUTO_UPLOAD: "${VSS_ENABLE_TWELVE_LABS_AUTO_UPLOAD}"
      
      # Core VSS Configuration
      ASSET_STORAGE_DIR: "${ASSET_STORAGE_DIR}"
      BACKEND_PORT: "${BACKEND_PORT}"
      FRONTEND_PORT: "${FRONTEND_PORT}"
      DISABLE_CV_PIPELINE: "${DISABLE_CV_PIPELINE}"
      DISABLE_FRONTEND: "${DISABLE_FRONTEND}"
      DISABLE_GUARDRAILS: "${DISABLE_GUARDRAILS}"
      DISABLE_CA_RAG: "${DISABLE_CA_RAG}"
      VLM_MODEL_TO_USE: "${VLM_MODEL_TO_USE}"
      VSS_LOG_LEVEL: "${VSS_LOG_LEVEL}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack: 67108864
    ipc: host
    stdin_open: true
    tty: true
    extra_hosts:
      host.docker.internal: host-gateway


volumes:
  via-hf-cache:
  via-ngc-model-cache: